//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstrumentMessagesHandlerTests.QCEvaluationServicesReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResult", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Common")]
    public enum RequestResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succesfull = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QCEvaluationServicesReference.IQCEvaluationService")]
    public interface IQCEvaluationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRule", ReplyAction="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRuleResponse")]
        QCEvaluation.WCFService.CreateStandardDeviationRuleResponse CreateStandardDeviationRule(QCEvaluation.WCFService.CreateStandardDeviationRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRule", ReplyAction="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRuleResponse")]
        System.Threading.Tasks.Task<QCEvaluation.WCFService.CreateStandardDeviationRuleResponse> CreateStandardDeviationRuleAsync(QCEvaluation.WCFService.CreateStandardDeviationRuleRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQCEvaluationServiceChannel : InstrumentMessagesHandlerTests.QCEvaluationServicesReference.IQCEvaluationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QCEvaluationServiceClient : System.ServiceModel.ClientBase<InstrumentMessagesHandlerTests.QCEvaluationServicesReference.IQCEvaluationService>, InstrumentMessagesHandlerTests.QCEvaluationServicesReference.IQCEvaluationService {
        
        public QCEvaluationServiceClient() {
        }
        
        public QCEvaluationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QCEvaluationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCEvaluationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCEvaluationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QCEvaluation.WCFService.CreateStandardDeviationRuleResponse CreateStandardDeviationRule(QCEvaluation.WCFService.CreateStandardDeviationRuleRequest request) {
            return base.Channel.CreateStandardDeviationRule(request);
        }
        
        public System.Threading.Tasks.Task<QCEvaluation.WCFService.CreateStandardDeviationRuleResponse> CreateStandardDeviationRuleAsync(QCEvaluation.WCFService.CreateStandardDeviationRuleRequest request) {
            return base.Channel.CreateStandardDeviationRuleAsync(request);
        }
    }
}
