//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabConfiguration.Adapters.QCEvaluationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateStandardDeviationRuleRequest", Namespace="http://schemas.datacontract.org/2004/07/QCEvaluation.WCFService")]
    [System.SerializableAttribute()]
    public partial class CreateStandardDeviationRuleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfControlsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StandardDeviationLimitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WithinControlValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfControls {
            get {
                return this.NumberOfControlsField;
            }
            set {
                if ((this.NumberOfControlsField.Equals(value) != true)) {
                    this.NumberOfControlsField = value;
                    this.RaisePropertyChanged("NumberOfControls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleName {
            get {
                return this.RuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleNameField, value) != true)) {
                    this.RuleNameField = value;
                    this.RaisePropertyChanged("RuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StandardDeviationLimits {
            get {
                return this.StandardDeviationLimitsField;
            }
            set {
                if ((this.StandardDeviationLimitsField.Equals(value) != true)) {
                    this.StandardDeviationLimitsField = value;
                    this.RaisePropertyChanged("StandardDeviationLimits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WithinControlValue {
            get {
                return this.WithinControlValueField;
            }
            set {
                if ((this.WithinControlValueField.Equals(value) != true)) {
                    this.WithinControlValueField = value;
                    this.RaisePropertyChanged("WithinControlValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateStandardDeviationRuleResponse", Namespace="http://schemas.datacontract.org/2004/07/QCEvaluation.WCFService")]
    [System.SerializableAttribute()]
    public partial class CreateStandardDeviationRuleResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LabConfiguration.Adapters.QCEvaluationServiceReference.RequestResult RequestResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabConfiguration.Adapters.QCEvaluationServiceReference.RequestResult RequestResult {
            get {
                return this.RequestResultField;
            }
            set {
                if ((this.RequestResultField.Equals(value) != true)) {
                    this.RequestResultField = value;
                    this.RaisePropertyChanged("RequestResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResult", Namespace="http://schemas.datacontract.org/2004/07/WCFServices.Common")]
    public enum RequestResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succesfull = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QCEvaluationServiceReference.IQCEvaluationService")]
    public interface IQCEvaluationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRule", ReplyAction="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRuleResponse")]
        LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleResponse CreateStandardDeviationRule(LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRule", ReplyAction="http://tempuri.org/IQCEvaluationService/CreateStandardDeviationRuleResponse")]
        System.Threading.Tasks.Task<LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleResponse> CreateStandardDeviationRuleAsync(LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCEvaluationService/NotifyApplicationInstalled", ReplyAction="http://tempuri.org/IQCEvaluationService/NotifyApplicationInstalledResponse")]
        void NotifyApplicationInstalled(int testCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCEvaluationService/NotifyApplicationInstalled", ReplyAction="http://tempuri.org/IQCEvaluationService/NotifyApplicationInstalledResponse")]
        System.Threading.Tasks.Task NotifyApplicationInstalledAsync(int testCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQCEvaluationServiceChannel : LabConfiguration.Adapters.QCEvaluationServiceReference.IQCEvaluationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QCEvaluationServiceClient : System.ServiceModel.ClientBase<LabConfiguration.Adapters.QCEvaluationServiceReference.IQCEvaluationService>, LabConfiguration.Adapters.QCEvaluationServiceReference.IQCEvaluationService {
        
        public QCEvaluationServiceClient() {
        }
        
        public QCEvaluationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QCEvaluationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCEvaluationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCEvaluationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleResponse CreateStandardDeviationRule(LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleRequest request) {
            return base.Channel.CreateStandardDeviationRule(request);
        }
        
        public System.Threading.Tasks.Task<LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleResponse> CreateStandardDeviationRuleAsync(LabConfiguration.Adapters.QCEvaluationServiceReference.CreateStandardDeviationRuleRequest request) {
            return base.Channel.CreateStandardDeviationRuleAsync(request);
        }
        
        public void NotifyApplicationInstalled(int testCode) {
            base.Channel.NotifyApplicationInstalled(testCode);
        }
        
        public System.Threading.Tasks.Task NotifyApplicationInstalledAsync(int testCode) {
            return base.Channel.NotifyApplicationInstalledAsync(testCode);
        }
    }
}
