//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstrumentMessagesHandlerTests.LabConfigurationServicesReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmApplicationInstallationRequest", Namespace="http://schemas.datacontract.org/2004/07/LabConfiguration.WCFService")]
    [System.SerializableAttribute()]
    public partial class ConfirmApplicationInstallationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicationTestCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationTestCode {
            get {
                return this.ApplicationTestCodeField;
            }
            set {
                if ((this.ApplicationTestCodeField.Equals(value) != true)) {
                    this.ApplicationTestCodeField = value;
                    this.RaisePropertyChanged("ApplicationTestCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmApplicationInstallationResponse", Namespace="http://schemas.datacontract.org/2004/07/LabConfiguration.WCFService")]
    [System.SerializableAttribute()]
    public partial class ConfirmApplicationInstallationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LabConfigurationServicesReference.ILabConfigurationService")]
    public interface ILabConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabConfigurationService/ConfirmApplicationInstallation", ReplyAction="http://tempuri.org/ILabConfigurationService/ConfirmApplicationInstallationRespons" +
            "e")]
        InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationResponse ConfirmApplicationInstallation(InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILabConfigurationService/ConfirmApplicationInstallation", ReplyAction="http://tempuri.org/ILabConfigurationService/ConfirmApplicationInstallationRespons" +
            "e")]
        System.Threading.Tasks.Task<InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationResponse> ConfirmApplicationInstallationAsync(InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILabConfigurationServiceChannel : InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ILabConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabConfigurationServiceClient : System.ServiceModel.ClientBase<InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ILabConfigurationService>, InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ILabConfigurationService {
        
        public LabConfigurationServiceClient() {
        }
        
        public LabConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationResponse ConfirmApplicationInstallation(InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationRequest request) {
            return base.Channel.ConfirmApplicationInstallation(request);
        }
        
        public System.Threading.Tasks.Task<InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationResponse> ConfirmApplicationInstallationAsync(InstrumentMessagesHandlerTests.LabConfigurationServicesReference.ConfirmApplicationInstallationRequest request) {
            return base.Channel.ConfirmApplicationInstallationAsync(request);
        }
    }
}
