//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace QCRoutine.Adapter.Service_References.QCRoutineServiceReference {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="QCResult", Namespace="http://schemas.datacontract.org/2004/07/QCRoutine.WCFService")]
    [Serializable()]
    public partial class QCResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private System.DateTime MeasuredDateField;
        
        [OptionalField()]
        private double ResultField;
        
        [OptionalField()]
        private int TestCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public System.DateTime MeasuredDate {
            get {
                return this.MeasuredDateField;
            }
            set {
                if ((this.MeasuredDateField.Equals(value) != true)) {
                    this.MeasuredDateField = value;
                    this.RaisePropertyChanged("MeasuredDate");
                }
            }
        }
        
        [DataMember()]
        public double Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [DataMember()]
        public int TestCode {
            get {
                return this.TestCodeField;
            }
            set {
                if ((this.TestCodeField.Equals(value) != true)) {
                    this.TestCodeField = value;
                    this.RaisePropertyChanged("TestCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="StoreQCResultResponse", Namespace="http://schemas.datacontract.org/2004/07/QCRoutine.WCFService")]
    [Serializable()]
    public partial class StoreQCResultResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [OptionalField()]
        private WCFServices.Common.RequestResult StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember()]
        public WCFServices.Common.RequestResult Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QCRoutineServiceReference.IQCRoutineService")]
    public interface IQCRoutineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCRoutineService/StoreQCResult", ReplyAction="http://tempuri.org/IQCRoutineService/StoreQCResultResponse")]
        StoreQCResultResponse StoreQCResult(QCResult request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQCRoutineService/StoreQCResult", ReplyAction="http://tempuri.org/IQCRoutineService/StoreQCResultResponse")]
        System.Threading.Tasks.Task<StoreQCResultResponse> StoreQCResultAsync(QCResult request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQCRoutineServiceChannel : IQCRoutineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QCRoutineServiceClient : System.ServiceModel.ClientBase<IQCRoutineService>, IQCRoutineService {
        
        public QCRoutineServiceClient() {
        }
        
        public QCRoutineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QCRoutineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCRoutineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QCRoutineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreQCResultResponse StoreQCResult(QCResult request) {
            return base.Channel.StoreQCResult(request);
        }
        
        public System.Threading.Tasks.Task<StoreQCResultResponse> StoreQCResultAsync(QCResult request) {
            return base.Channel.StoreQCResultAsync(request);
        }
    }
}
